//@ui5-bundle br/com/fcc/co/custosegregado2/composicaodecustos/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"br/com/fcc/co/custosegregado2/composicaodecustos/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","br/com/fcc/co/custosegregado2/composicaodecustos/model/models"],function(e,o,t){"use strict";return e.extend("br.com.fcc.co.custosegregado2.composicaodecustos.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(t.createDeviceModel(),"device")}})});
},
	"br/com/fcc/co/custosegregado2/composicaodecustos/controller/Main.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel"],function(e,t){"use strict";return e.extend("br.com.fcc.co.custosegregado2.composicaodecustos.controller.Main",{onInit:function(){var e=this.getView().getModel("oDataModel");var o=this;e.callFunction("/getCurrentUser",{method:"GET",urlParameters:{},success:function(e,s){var a={Timestamp:new Date,Username:e.Username,Name:e.Name};var r=new t(a);o.getView().setModel(r)}})},composicaoDeCustos:function(e){var t=this.getView().byId("periodo").getDateValue().getMonth()+1;var o=this.getView().byId("periodo").getDateValue().getFullYear();var s=this.getView().getModel("oDataModel");var a=this;s.callFunction("/composicaoDeCustos",{method:"POST",urlParameters:{poper:t,bdatj:o},success:function(e,t){sap.m.MessageToast.show(a.getView().getModel("i18n").getProperty("messageSuccess"))},error:function(e){sap.m.MessageToast.show(a.getView().getModel("i18n").getProperty("messageError"))}})}})});
},
	"br/com/fcc/co/custosegregado2/composicaodecustos/i18n/i18n.properties":'title=Custos segregados\nappTitle=Custos segregados\nappDescription=Apura\\u00e7\\u00e3o dos custos segregados\nperiodo=Selecione ano e per\\u00edodo cont\\u00e1bil\nexecutar=Executar\nexecutarText=Inicia apura\\u00e7\\u00e3o dos custos\nmessageSuccess=Composi\\u00e7\\u00e3o de custos realizada com sucesso\nmessageError=Erro interno. Contate o administrador do sistema\ncreatedByLabel=Criado por\ncreatedAtLabel=Criado em',
	"br/com/fcc/co/custosegregado2/composicaodecustos/localService/mockserver.js":function(){sap.ui.define(["sap/ui/core/util/MockServer","sap/ui/model/json/JSONModel","sap/base/util/UriParameters","sap/base/Log"],function(e,t,r,a){"use strict";var o,i="br.com.fcc.co.custosegregado2.composicaodecustos/",n=i+"localService/mockdata";var s={init:function(s){var u=s||{};return new Promise(function(s,c){var p=sap.ui.require.toUrl(i+"manifest.json"),f=new t(p);f.attachRequestCompleted(function(){var t=new r(window.location.href),c=sap.ui.require.toUrl(n),p=f.getProperty("/sap.app/dataSources/mainService"),l=sap.ui.require.toUrl(i+p.settings.localUri),d=p.uri&&new URI(p.uri).absoluteTo(sap.ui.require.toUrl(i)).toString();if(!o){o=new e({rootUri:d})}else{o.stop()}e.config({autoRespond:true,autoRespondAfter:u.delay||t.get("serverDelay")||500});o.simulate(l,{sMockdataBaseUrl:c,bGenerateMissingMockData:true});var m=o.getRequests();var g=function(e,t,r){r.response=function(r){r.respond(e,{"Content-Type":"text/plain;charset=utf-8"},t)}};if(u.metadataError||t.get("metadataError")){m.forEach(function(e){if(e.path.toString().indexOf("$metadata")>-1){g(500,"metadata Error",e)}})}var v=u.errorType||t.get("errorType"),h=v==="badRequest"?400:500;if(v){m.forEach(function(e){g(h,v,e)})}o.setRequests(m);o.start();a.info("Running the app with mock data");s()});f.attachRequestFailed(function(){var e="Failed to load application manifest";a.error(e);c(new Error(e))})})},getMockServer:function(){return o}};return s});
},
	"br/com/fcc/co/custosegregado2/composicaodecustos/manifest.json":'{"_version":"1.32.0","sap.app":{"id":"br.com.fcc.co.custosegregado2.composicaodecustos","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","ach":"ach","dataSources":{"mainService":{"uri":"/sap/opu/odata/sap/ZCO_CUSTO_SEGREGADO_BI_SRV","type":"OData","settings":{"odataVersion":"2.0","localUri":"localService/metadata.xml"}}}},"sap.ui":{"technology":"UI5","icons":{"icon":"sap-icon://task","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"br.com.fcc.co.custosegregado2.composicaodecustos.view.Main","type":"XML","async":true,"id":"Main"},"dependencies":{"minUI5Version":"1.66.0","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"br.com.fcc.co.custosegregado2.composicaodecustos.i18n.i18n"}},"oDataModel":{"dataSource":"mainService","preload":true}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"br.com.fcc.co.custosegregado2.composicaodecustos.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteMain","pattern":"RouteMain","target":["TargetMain"]}],"targets":{"TargetMain":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"Main","viewName":"Main"}}}}}',
	"br/com/fcc/co/custosegregado2/composicaodecustos/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"br/com/fcc/co/custosegregado2/composicaodecustos/view/Main.view.xml":'<mvc:View\n    controllerName="br.com.fcc.co.custosegregado2.composicaodecustos.controller.Main"\n    xmlns:mvc="sap.ui.core.mvc"\n    displayBlock="true"\n    xmlns="sap.m"\n\txmlns:f="sap.ui.layout.form"\n><Shell id="shell"><App id="app"><pages><Page class="sapUiResponsivePadding" id="page" title="{i18n>title}"><Panel><VBox><f:SimpleForm\n\t\t\t\t\t\t\t\tlayout="ResponsiveGridLayout"\n\t\t\t\t\t\t\t\tadjustLabelSpan="false"\n\t\t\t\t\t\t\t\tsingleContainerFullSize="false"\n\t\t\t\t\t\t\t\teditable="false"><f:content><Label text="{i18n>periodo}" labelFor="periodo"/><DatePicker\n\t\t\t\t\t\t\t\t\t\tid="periodo"\n\t\t\t\t\t\t\t\t\t\tplaceholder="Selecione.."\n\t\t\t\t\t\t\t\t\t\tdisplayFormat="MM-yyyy"/><Label text="{i18n>createdAtLabel}" labelFor="DateText"/><Text id="DateText" text="{\n\t\t\t\t\t\t\t\t\t\t\t\t\tpath: \'/Timestamp\',\n\t\t\t\t\t\t\t\t\t\t\t\t\ttype: \'sap.ui.model.type.DateTime\',\n\t\t\t\t\t\t\t\t\t\t\t\t\tformatOptions: {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tpattern: \'dd/MM/yyyy\'\n\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t\t\t\t}" /><Label text="{i18n>createdByLabel}" labelFor="UserText"/><Text id="UserText" text="{/Username} - {/Name}" /><Label text="" labelFor="submitBtn" /><Button id="submitBtn" icon="sap-icon://create" press="composicaoDeCustos" text="{i18n>executar}"/></f:content></f:SimpleForm></VBox></Panel></Page></pages></App></Shell></mvc:View>\n'
}});
